name: CI learning(FastAPI)


on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: "3.12"

    - name: Install Dependencies
      run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest black

    - name: Run Tests
      run: |
          source venv/bin/activate
          pytest CI/CD_learning/tests

    - name: Code Formatting Check
      run: |
          source venv/bin/activate
          black --check .
